# Generated by Django 4.2.4 on 2023-08-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('habitat', models.CharField(choices=[('F', 'Forest'), ('A', 'Arctic Tundra'), ('D', 'Desert')], default='F', max_length=1)),
            ],
        ),
    ]
