# Generated by Django 4.2.4 on 2023-08-08 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_habitats'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitats',
            name='fox',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.fox'),
        ),
        migrations.AlterField(
            model_name='habitats',
            name='date',
            field=models.DateField(verbose_name='date discovered'),
        ),
    ]
