# Generated by Django 4.2.4 on 2023-08-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_habitats_fox_alter_habitats_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitats',
            options={'verbose_name_plural': 'Habitats'},
        ),
    ]
