# Generated by Django 4.2.4 on 2023-08-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='fox',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
